Documents/GitHub/emotion-notebook/views.py
#！urs/bin/env python3
# coding=utf-8

from  flask import render_template, Blueprint, redirect, url_for, flash, request
from run import login_manger
from form import Login_Form, Register_Form
from model import  Users
from flask_login import LoginManager, login_user, UserMixin, logout_user, login_required
from run import db
import time

from note_db import insert_data, obtain_data, get_history, update
from rad import rand

date = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())


eNote=Blueprint('eNote', __name__, template_folder='templates')  #蓝图

@eNote.route('/login', methods=['GET'])
def index():
    form=Login_Form()
    return render_template('login.html', form=form)


@eNote.route('/login',methods=['POST'])
def login():
        form=Login_Form()
        if form.validate_on_submit():
            user=Users.query.filter_by(username=form.name.data).first()
            if user is not  None and user.password==form.pwd.data:
                login_user(user)
                flash('登录成功')
                return  render_template('hello.html', name=form.name.data)
            else:
                flash('用户或密码错误')
                return render_template('login.html', form=form)

#用户登出
@eNote.route('/logout')
@login_required
def logout():
    logout_user()
    flash('你已退出登录')
    return redirect(url_for('eNote.index'))


@eNote.route('/register', methods=['GET','POST'])
def register():
    form=Register_Form()
    if form.validate_on_submit():
        user=Users(username=form.name.data, password=form.pwd.data)
        db.session.add(user)
        db.session.commit()
        flash('注册成功')
        return redirect(url_for('eNote.index'))
    return render_template('register.html', form=form)

#from graduation

@eNote.route('/', methods = ['GET', 'POST'])
def home():
    return render_template('start.html')

@eNote.route('/start', methods = ['GET', 'POST'])
def start():
    return render_template('index.html', date = date)

@eNote.route('/write', methods = ['GET', 'POST'])
def record():
    name = request.args.get('name')
    event = request.args.get('event')

    scenes = request.args.get('scenes')
        # 把列表转换为字符串，字符串相加
    relationship = '/'.join(request.values.getlist("relationship"))
    mood = '/'.join(request.values.getlist("mood"))
    mood_t = '    '.join(request.values.getlist("mood"))
    feel = '/'.join(request.values.getlist("feel"))
    user_write = "在{}，{}，我感到{}，{},".format(scenes, event, mood, feel)

    ent = ' '.join(request.values.getlist('ent'))

    reason = request.args.get("reason")

    understanding = request.args.get("understanding")

    next_write = "{}，我做了（想做）{}，\n我的理解：{}".format(user_write, ent, understanding)

    encour = rand()
    if request.args.get('submit') == "完成":

        insert_data(name, date, next_write)
        return render_template('sex.html', encour = encour, mood_t = mood_t)


@eNote.route('/404', methods = ["GET", "POST"])
def back():
    if request.args.get('submit') == "返回":
        return render_template('index.html')

@eNote.route('/note', methods = ["GET", "POST"])
def note():
    if request.args.get('submit') == "返回":
        return render_template('index.html', date = date)

@eNote.route('/happy', methods = ["GET", "POST"])
def happy():
    return render_template("happy.html", date = date)

@eNote.route('/end', methods = ["GET", "POST"])
def next():
    if request.args.get('submit') == "完成":
        name = request.args.get('name')
        happy_thing = request.args.get("happy_thing")
        insert_data(name, date, happy_thing)
        return render_template('recording_happy.html')

@eNote.route('/recording', methods = ["GET", "POST"])
def recording():
    if request.args.get('submit') == "返回":
        return render_template('index.html', date = date)

@eNote.route('/one', methods = ["GET", "POST"])
def history():
    history = get_history()
    return render_template('oneself.html', history = history)

@eNote.route('/online', methods = ["GET", "POST"])
def online():
    if request.args.get('submit') == "返回":
        return render_template('index.html')

Documents/GitHub/emotion-notebook/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

<title>Hello,friends!</title>
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
<link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
<!-- Bootstrap core CSS -->


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="/static/css/navbar-fixed-top.css" rel="stylesheet">

<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
<script src="/static/js/ie-emulation-modes-warning.js"></script>

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">心情日记</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/eNote">Home</a></li>
                <li><a href="happy">好心情</a></li>
                <li><a href="start">坏心情</a></li>
            </ul>

              <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('eNote.logout') }}">退出</a></li>
                {% else %}
                <li><a href="{{ url_for('eNote.index') }}">登录</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('eNote.register') }}">注册</a></li>

            </ul>


        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <br><br><br>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}

<!-- Bootstrap core JavaScript
   ================================================== -->
   <!-- Placed at the end of the document so the pages load faster -->

   <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
   <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
   <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
</html>

{% endblock %}

Documents/GitHub/emotion-notebook/templates/happy.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
            <meta name="description" content="">
            <meta name="author" content="">

        <title>good</title>
        <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
	    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
        <link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap core CSS -->


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/static/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body background={{url_for('static', filename='background2.png')}}>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="">心情日记</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                  <li><a href="/eNote">Home</a></li>
                <li class="active"><a href="happy">好心情</a></li>
                <li><a href="start">坏心情</a></li>

            </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="login">登录/注册</a></li>
                <li><a href="logout">注销</a></li>
                <li class="active"><a href="one">日记<span class="sr-only">(current)</span></a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <br><br><br>
        <form action="happy" method="get">/</form>
        <form action="end" method="get">
        <div class="step-content">

                <!-- 标题头介绍 -->
                <div>
                    <h4 class="margin-lg-left">时间：{{date}}</h4>
                    <h4 class="margin-lg-left">请为自己填写一个昵称：<input type="text" name="name"></h4>
                </div>

        </div>

        <br><br>
        <div class="container fuelux">


                    <div class="panel panel-default">
                  <!-- Default panel contents -->
                  <div class="panel-heading">快乐预测表</div>
                  <!-- Table -->
                  <table class="table table-bordered">

                  <thead>
                      <tr>
                        <th>日期</th>
                        <th>活动类型（特指使你能够产生成就感或快乐的东西）</th>
                        <th>陪你完成活动的人（如果是独自一人，请写明“我自己”）</th>
                        <th>预计快乐程度（0%-100%）(活动开始前填写)</th>
                        <th>实际快乐程度（0%-100%）（活动结束后填写）</th>

                      </tr>
                  </thead>
                  <tbody>
                      <tr>
                        <td>例如：1999/4/18</td>
                        <td>做咨询项目</td>
                        <td>我自己</td>
                        <td>70%</td>
                        <td>80%</td>

                      </tr>
                      <tr>
                        <td><input type="text" name="end" placeholder="请填写..."></td>
                        <td><input type="text" name="end2" placeholder="请填写..."></td>
                        <td><input type="text" name="end3" placeholder="请填写..."></td>
                        <td><input type="text" name="end4" placeholder="请填写..."></td>
                        <td><input type="text" name="end5" placeholder="请填写..."></td>
                      </tr>
                  </tbody>
                  </table>
                </div>
            </div>
        <div class="row sel-group">
            <div class="col-md-12">
                <p class="text-left sel-title"><font size="4" face="arial">记录细小快乐事件</font></p>
            </div>
            <div class="col-md-10 col-md-offset-1">
                <textarea class="form-control" rows="5" name="happy_thing" style="margin-bottom: 6px;" placeholder="提示：想怎么写就怎么写~在这里就是让你随意"></textarea>
            </div>
        </div>
    </div>

    <div class="steps-container text-center">
        <input type="submit" align="center" name="submit" value="完成" class="btn btn-primary btn-next">
    </div>
    </form>


    </body>
    <script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/fuelux/fuelux.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>

</html>

Documents/GitHub/emotion-notebook/templates/hello.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


{% block page_content %}
 <div class="page-header">
    <div class="jumbotron in" id="header">
        <h1>欢迎来到心情日记！</h1>
        <p>在这里，也许你可以重新认识到自己，先给自己一个微笑吧^_^</p>
        <p>根据提示，做选择填空，朋友放轻松，不是考试哦~</p>
        <p>嘿~朋友，看哪呢，看导航条啊，有心情分类，别走错了哟~</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button"
              data-toggle="collapse" data-target="#form_content,#header" aria-expanded="false" aria-controls="form_content">让我们开始吧</a></p>
    </div>
</div>

{% endblock %}
</body>
</html>

Documents/GitHub/emotion-notebook/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Flasky{% endblock %}
{% block page_content %}

<div class="page-header">
 <h1>心情日记</h1>
</div>
    <form action="login" method="post">
    {{ wtf.quick_form(form) }}

    </form>

{% endblock %}

Documents/GitHub/emotion-notebook/templates/oneself.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>hello,frind^_^</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
        <link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
    </head>
    <body background={{url_for('static', filename='background2.png')}}>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="">心情日记</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/eNote">Home</a></li>
                <li><a href="happy">好心情</a></li>
                <li><a href="start">坏心情</a></li>

            </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="login">登录/注册</a></li>
                <li><a href="logout">注销</a></li>
                <li><a href="one">日记</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <br><br><br>

        <form action="one" method="get"></form>
        <div align="center">
            <img src="{{ url_for('static', filename='be_happy.jpg') }}" alt="心情图片" widt ="500" high="250">
            <br><br>
            <p><font size="5" face="arial">
                {% for line in history %}
                {{ line }}<br>
                {% endfor %}
            </font></p>
            <br><br>

            <form action="online" method="get">
                <div class="steps-container text-center">
                    <input type="submit" align="center" name="submit" value="返回" class="btn btn-primary btn-next">
                </div>

            </form>
        </div>

    </body>
</html>

Documents/GitHub/emotion-notebook/templates/recording_happy.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
            <meta name="description" content="">
            <meta name="author" content="">

        <title>Hello,friends!</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
        <link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap core CSS -->


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/static/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body background={{url_for('static', filename='background2.png')}}>
        <!-- Fixed navbar -->
       <nav class="navbar navbar-default navbar-fixed-top">
         <div class="container">
           <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="/">心情日记</a>
           </div>
           <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
               <li class="active"><a href="/eNote">Home</a></li>
               <li><a href="happy">好心情</a></li>
               <li><a href="start">坏心情</a></li>

           </ul>
             <ul class="nav navbar-nav navbar-right">
               <li><a href="login">登录/注册</a></li>
               <li><a href="logout">注销</a></li>
               <li class="active"><a href="one">Home<span class="sr-only">(current)</span></a></li>
             </ul>
           </div><!--/.nav-collapse -->
         </div>
       </nav>
       <br><br><br>
       <div class="container fuelux">
    <div class="jumbotron in" id="header">
        <h1>朋友，感谢使用！</h1>
        <p>记录成功，希望您一直开心下去哟~</p>
        <p><a class="btn btn-primary btn-lg" href="/" role="button"
              data-toggle="collapse" data-target="#form_content,#header" aria-expanded="false" aria-controls="form_content">结束</a></p>
    </div>
    </div>
    </body>
</html>

Documents/GitHub/emotion-notebook/templates/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Flasky{% endblock %}
{% block page_content %}

<div class="page-header">
 <h1>注册</h1>
</div>
    <form action="register" method="post">
    {{ wtf.quick_form(form) }}

    </form>

{% endblock %}

Documents/GitHub/emotion-notebook/templates/sex.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>hello,frind^_^</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
        <link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
    </head>
    <body background={{url_for('static', filename='background2.png')}}>
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">心情日记</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/eNote">Home</a></li>
                <li><a href="happy">好心情</a></li>
                <li><a href="start">坏心情</a></li>

            </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="login">登录/注册</a></li>
                <li><a href="logut">注销</a></li>
                <li><a href="one">日记</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </nav>
        <br><br><br>
        <div align="center">
            <img src="{{ url_for('static', filename='be_happy.jpg') }}" alt="心情图片" class="img-circle" widt ="500" high="250">
            <br><br>
            <p><font size="5" face="arial" color="red">{{encour}}</font></p>
            <br><br>
            <p><font size="5" face="arial">您之前的情绪为：{{mood_t}}</font></p>
            <div class="row sel-group">
                <div class="col-md-12">
                    <p class="text-left sel-title"><font size="4" face="arial">再次感受情绪所占百分比</font></p>
                </div>
                <div class="col-md-10 col-md-offset-1">
                    <textarea class="form-control" rows="5" name="understanding" style="margin-bottom: 6px;" placeholder="提示：想怎么写就怎么写~在这里就是让你随意"></textarea>
                </div>
            </div>
            <br>
            <p></p>
            <form action="note">
                <div class="steps-container text-center">
                    <input type="submit" align="center" name="submit" value="返回" class="btn btn-primary btn-next">
                </div>

            </form>
        </div>
    </body>
</html>

Documents/GitHub/emotion-notebook/templates/start.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
            <meta name="description" content="">
            <meta name="author" content="">

        <title>Hello,friends!</title>
        <link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <!--<link href="/static/css/awesome/font-awesome.css" rel="stylesheet" type="text/css"/>-->
        <link href="/static/css/fuelux/fuelux.min.css" rel="stylesheet" type="text/css"/>
        <link href="/static/css/index.css" rel="stylesheet" type="text/css"/>
        <!-- Bootstrap core CSS -->


        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="/static/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body background={{url_for('static', filename='background2.png')}}>
        <!-- Fixed navbar -->
       <nav class="navbar navbar-default navbar-fixed-top">
         <div class="container">
           <div class="navbar-header">
             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand active" href="">心情日记</a>
           </div>
           <div id="navbar" class="navbar-collapse collapse">
             <ul class="nav navbar-nav">
               <li class="active"><a href="/eNote">Home</a></li>
               <li><a href="happy">好心情</a></li>
               <li><a href="start">坏心情</a></li>

           </ul>
             <ul class="nav navbar-nav navbar-right">
               <li><a href="login">登录/注册</a></li>
               <li><a href="logout">注销</a></li>
               <li><a href="one">日记</a></li>
             </ul>
           </div><!--/.nav-collapse -->
         </div>
       </nav>
       <br><br><br>
<div class="container fuelux">
    <form action="start" method="get">
    <div class="jumbotron in" id="header">
        <h1>欢迎来到心情日记！</h1>
        <p>在这里，也许你可以重新认识到自己，先给自己一个微笑吧^_^</p>
        <p>根据提示，做选择填空，朋友放轻松，不是考试哦~</p>
        <p>嘿~朋友，看哪呢，看导航条啊，有心情分类，别走错了哟~</p>
        <p><a class="btn btn-primary btn-lg" href="start" role="button"
              data-toggle="collapse" data-target="#form_content,#header" aria-expanded="false" aria-controls="form_content">让我们开始吧</a></p>
    </div>
</form>
</div>
</body>
</html>